import React, { useState } from 'react';
import {
  Play,
  RotateCcw,
  Sparkles,
  Sliders,
  Activity,
  Clock,
  Fuel,
  Leaf,
  CheckCircle2,
  Cpu,
  Layers,
  TrendingDown,
  AlertTriangle,
  Info,
} from 'lucide-react';
import { simulationService } from '../services/simulationService';
import { SimulationConfig, SimulationResult } from '../models/traffic';
import { INDIA_CITIES } from '../data/indiaCities';

export const SimulationSandboxView: React.FC = () => {
  const [city, setCity] = useState('Vijayawada');
  const [intersectionCount, setIntersectionCount] = useState(6);
  const [trafficIntensity, setTrafficIntensity] = useState<SimulationConfig['trafficIntensity']>('PEAK_EVENING');
  const [weather, setWeather] = useState<SimulationConfig['weather']>('RAIN');
  const [specialEvent, setSpecialEvent] = useState<SimulationConfig['specialEvent']>('IPL_CRICKET_MATCH');

  const [isRunning, setIsRunning] = useState(false);
  const [simStep, setSimStep] = useState<'IDLE' | 'INGESTING' | 'PREDICTING' | 'OPTIMIZING' | 'COMPLETED'>('IDLE');
  const [simResult, setSimResult] = useState<SimulationResult | null>(() => {
    return simulationService.runSimulation({
      city: 'Vijayawada',
      intersectionCount: 6,
      trafficIntensity: 'PEAK_EVENING',
      weather: 'RAIN',
      specialEvent: 'IPL_CRICKET_MATCH',
      durationMinutes: 60,
    });
  });

  const handleRunSimulation = () => {
    setIsRunning(true);
    setSimStep('INGESTING');

    setTimeout(() => {
      setSimStep('PREDICTING');
      setTimeout(() => {
        setSimStep('OPTIMIZING');
        setTimeout(() => {
          const res = simulationService.runSimulation({
            city,
            intersectionCount,
            trafficIntensity,
            weather,
            specialEvent,
            durationMinutes: 60,
          });
          setSimResult(res);
          setSimStep('COMPLETED');
          setIsRunning(false);
        }, 600);
      }, 600);
    }, 600);
  };

  return (
    <div className="space-y-6">
      {/* Prominent Demo Mode Disclaimer Banner */}
      <div className="p-4 bg-amber-500 text-slate-950 rounded-2xl shadow-sm flex items-center justify-between gap-4 font-bold text-xs">
        <div className="flex items-center gap-2.5">
          <AlertTriangle className="w-5 h-5 shrink-0" />
          <span>
            DEMO / SIMULATION MODE: All numerical calculations on this page are generated by mathematical heuristics for prototype evaluation.
          </span>
        </div>
        <span className="text-[11px] font-mono uppercase bg-slate-950 text-white px-2 py-0.5 rounded">
          Heuristic Sandbox
        </span>
      </div>

      {/* Top Header */}
      <div className="p-6 bg-[#0b192c] text-white rounded-2xl shadow-sm flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-purple-400 text-xs font-semibold tracking-wider">
            <Cpu className="w-4 h-4" />
            <span>METROPOLITAN TRAFFIC SIMULATION SANDBOX</span>
          </div>
          <h2 className="text-xl font-bold mt-1">
            Custom Scenario Traffic Simulator
          </h2>
          <p className="text-xs text-slate-300 mt-1 max-w-2xl leading-relaxed">
            Configure urban crisis loads, extreme monsoon conditions, or stadium egress surges to simulate before vs after Webster split efficacy.
          </p>
        </div>

        <button
          disabled={isRunning}
          onClick={handleRunSimulation}
          className={`px-6 py-2.5 rounded-xl font-extrabold text-xs shadow-md transition-all flex items-center gap-2 cursor-pointer ${
            isRunning
              ? 'bg-purple-900 text-purple-300 cursor-not-allowed'
              : 'bg-purple-600 hover:bg-purple-500 text-white'
          }`}
        >
          <Play className="w-4 h-4" />
          <span>{isRunning ? 'SIMULATING LOAD...' : 'RUN SIMULATION'}</span>
        </button>
      </div>

      {/* Simulator Inputs Grid */}
      <div className="p-6 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-4">
        <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
          <Sliders className="w-4 h-4 text-purple-600" />
          Simulation Scenario Parameters
        </h3>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4 text-xs">
          {/* Target City */}
          <div>
            <label className="text-slate-500 font-semibold block mb-1">Target City</label>
            <select
              value={city}
              onChange={(e) => setCity(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-bold text-slate-900 focus:outline-none focus:border-purple-500 cursor-pointer"
            >
              {INDIA_CITIES.map((c) => (
                <option key={c.id} value={c.name}>
                  {c.name} ({c.state})
                </option>
              ))}
            </select>
          </div>

          {/* Number of Intersections */}
          <div>
            <div className="flex justify-between items-center mb-1">
              <label className="text-slate-500 font-semibold">Intersections</label>
              <span className="font-mono text-purple-600 font-bold">{intersectionCount}</span>
            </div>
            <input
              type="range"
              min={2}
              max={16}
              value={intersectionCount}
              onChange={(e) => setIntersectionCount(Number(e.target.value))}
              className="w-full accent-purple-600 cursor-pointer mt-1.5"
            />
          </div>

          {/* Traffic Intensity */}
          <div>
            <label className="text-slate-500 font-semibold block mb-1">Traffic Intensity</label>
            <select
              value={trafficIntensity}
              onChange={(e) => setTrafficIntensity(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-bold text-slate-900 focus:outline-none focus:border-purple-500 cursor-pointer"
            >
              <option value="LOW">Low (Late Night)</option>
              <option value="NORMAL">Normal Flow</option>
              <option value="PEAK_EVENING">Peak Evening Commute</option>
              <option value="MONSOON_CRISIS">Monsoon Waterlogging</option>
              <option value="FESTIVAL_RUSH">Festival / Deepavali Rush</option>
            </select>
          </div>

          {/* Weather */}
          <div>
            <label className="text-slate-500 font-semibold block mb-1">Weather Condition</label>
            <select
              value={weather}
              onChange={(e) => setWeather(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-bold text-slate-900 focus:outline-none focus:border-purple-500 cursor-pointer"
            >
              <option value="CLEAR">Clear Skies</option>
              <option value="RAIN">Heavy Monsoon Rain</option>
              <option value="FOG">Dense Winter Fog</option>
              <option value="HEATWAVE">Summer Heatwave</option>
            </select>
          </div>

          {/* Special Event */}
          <div>
            <label className="text-slate-500 font-semibold block mb-1">Special Urban Event</label>
            <select
              value={specialEvent}
              onChange={(e) => setSpecialEvent(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg p-2 font-bold text-slate-900 focus:outline-none focus:border-purple-500 cursor-pointer"
            >
              <option value="NONE">None (Regular Day)</option>
              <option value="IPL_CRICKET_MATCH">IPL Cricket Match</option>
              <option value="RELIGIOUS_PROCESSION">Religious Procession</option>
              <option value="VIP_CONVOY">VIP Movement Convoy</option>
            </select>
          </div>
        </div>
      </div>

      {/* Stepper progress if running */}
      {isRunning && (
        <div className="p-4 rounded-xl bg-purple-50 border border-purple-200 flex items-center justify-around text-xs animate-pulse font-semibold">
          <span className={simStep === 'INGESTING' ? 'text-purple-700 font-bold' : 'text-slate-400'}>
            1. Ingesting Road Network
          </span>
          <span className="text-slate-300">→</span>
          <span className={simStep === 'PREDICTING' ? 'text-purple-700 font-bold' : 'text-slate-400'}>
            2. Computing Arrival Curves
          </span>
          <span className="text-slate-300">→</span>
          <span className={simStep === 'OPTIMIZING' ? 'text-purple-700 font-bold' : 'text-slate-400'}>
            3. Synthesizing Green Splits
          </span>
        </div>
      )}

      {/* Simulation Results Display */}
      {simResult && (
        <div className="space-y-6">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs">
              <span className="text-xs text-slate-500 block mb-1">Simulated Delay Cut</span>
              <div className="text-2xl font-bold font-mono text-emerald-600">
                ↓ {simResult.improvement.waitingTimeReductionPercent}%
              </div>
              <span className="text-[11px] text-slate-400 font-mono">
                {simResult.before.avgWaitingTimeSec}s → {simResult.after.avgWaitingTimeSec}s
              </span>
            </div>

            <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs">
              <span className="text-xs text-slate-500 block mb-1">Simulated Congestion</span>
              <div className="text-2xl font-bold font-mono text-blue-600">
                ↓ {simResult.improvement.congestionReductionPercent}%
              </div>
              <span className="text-[11px] text-slate-400 font-mono">
                {simResult.before.avgCongestionPercent}% → {simResult.after.avgCongestionPercent}%
              </span>
            </div>

            <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs">
              <span className="text-xs text-slate-500 block mb-1">Speed Multiplier</span>
              <div className="text-2xl font-bold font-mono text-teal-600">
                +{simResult.improvement.speedIncreasePercent}%
              </div>
              <span className="text-[11px] text-slate-400 font-mono">
                {simResult.before.avgSpeedKmh} → {simResult.after.avgSpeedKmh} km/h
              </span>
            </div>

            <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs">
              <span className="text-xs text-slate-500 block mb-1">Model Fuel Conserved</span>
              <div className="text-2xl font-bold font-mono text-emerald-700">
                {simResult.improvement.fuelSavedLiters} L/hr
              </div>
              <span className="text-[11px] text-slate-400 font-mono">
                Avoids {simResult.improvement.co2MitigatedKg} kg CO₂
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 bg-white border border-rose-200 rounded-2xl shadow-xs space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-rose-100">
                <span className="text-xs font-bold text-rose-700 uppercase">
                  BEFORE AI (FIXED-TIME SCHEDULES)
                </span>
                <span className="text-[11px] text-slate-400 font-mono">Traditional Timers</span>
              </div>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between p-2 rounded-lg bg-slate-50">
                  <span className="text-slate-600">Waiting Time:</span>
                  <span className="font-mono text-rose-600 font-bold">{simResult.before.avgWaitingTimeSec}s</span>
                </div>
                <div className="flex justify-between p-2 rounded-lg bg-slate-50">
                  <span className="text-slate-600">Congestion Severity:</span>
                  <span className="font-mono text-rose-600 font-bold">{simResult.before.avgCongestionPercent}%</span>
                </div>
                <div className="flex justify-between p-2 rounded-lg bg-slate-50">
                  <span className="text-slate-600">Average Speed:</span>
                  <span className="font-mono text-slate-800">{simResult.before.avgSpeedKmh} km/h</span>
                </div>
              </div>
            </div>

            <div className="p-6 bg-white border border-emerald-200 rounded-2xl shadow-xs space-y-3">
              <div className="flex items-center justify-between pb-2 border-b border-emerald-100">
                <span className="text-xs font-bold text-emerald-700 uppercase flex items-center gap-1">
                  <Sparkles className="w-3.5 h-3.5" />
                  AFTER SMARTFLOW AI ADAPTATION
                </span>
                <span className="text-[11px] text-emerald-600 font-mono">Dynamic Webster Splits</span>
              </div>
              <div className="space-y-2 text-xs">
                <div className="flex justify-between p-2 rounded-lg bg-emerald-50">
                  <span className="text-slate-600">Waiting Time:</span>
                  <span className="font-mono text-emerald-700 font-bold">{simResult.after.avgWaitingTimeSec}s</span>
                </div>
                <div className="flex justify-between p-2 rounded-lg bg-emerald-50">
                  <span className="text-slate-600">Congestion Severity:</span>
                  <span className="font-mono text-emerald-700 font-bold">{simResult.after.avgCongestionPercent}%</span>
                </div>
                <div className="flex justify-between p-2 rounded-lg bg-emerald-50">
                  <span className="text-slate-600">Average Speed:</span>
                  <span className="font-mono text-cyan-700 font-bold">{simResult.after.avgSpeedKmh} km/h</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
